"""Initial migration

Revision ID: f11e6ed44e28
Revises: 
Create Date: 2023-08-12 08:46:36.663838+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11e6ed44e28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Логическое удаление объекта'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_roles')),
    sa.UniqueConstraint('name', name=op.f('UQ_roles_name')),
    schema='public'
    )
    op.create_index(op.f('IX_public_roles_created_at'), 'roles', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('IX_public_roles_updated_at'), 'roles', ['updated_at'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Password'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='Role id'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Логическое удаление объекта'),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], name=op.f('FK_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_users')),
    sa.UniqueConstraint('email', name=op.f('UQ_users_email')),
    schema='public'
    )
    op.create_index(op.f('IX_public_users_created_at'), 'users', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('IX_public_users_updated_at'), 'users', ['updated_at'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_public_users_updated_at'), table_name='users', schema='public')
    op.drop_index(op.f('IX_public_users_created_at'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('IX_public_roles_updated_at'), table_name='roles', schema='public')
    op.drop_index(op.f('IX_public_roles_created_at'), table_name='roles', schema='public')
    op.drop_table('roles', schema='public')
    # ### end Alembic commands ###
