"""Initial migration

Revision ID: 8681e8dedd14
Revises: 
Create Date: 2023-08-12 15:40:09.801014+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8681e8dedd14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('name', sa.String(length=255), nullable=True, comment='Name'),
    sa.Column('role', sa.String(length=255), nullable=False, comment='Role'),
    sa.Column('sso_id', sa.BigInteger(), nullable=False, comment='SSO ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Логическое удаление объекта'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_employee')),
    schema='public'
    )
    op.create_index(op.f('IX_public_employee_created_at'), 'employee', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('IX_public_employee_updated_at'), 'employee', ['updated_at'], unique=False, schema='public')
    op.create_table('task',
    sa.Column('description', sa.String(length=255), nullable=True, comment='Description'),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'DONE', name='status', schema='public'), nullable=False, comment='Status'),
    sa.Column('fee', sa.BigInteger(), nullable=False, comment='Fee'),
    sa.Column('payment', sa.BigInteger(), nullable=False, comment='Payment'),
    sa.Column('employee_id', sa.BigInteger(), nullable=False, comment='Employee id'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Идентификатор'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего обновления'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Логическое удаление объекта'),
    sa.ForeignKeyConstraint(['employee_id'], ['public.employee.id'], name=op.f('FK_task_employee_id_employee')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_task')),
    schema='public'
    )
    op.create_index(op.f('IX_public_task_created_at'), 'task', ['created_at'], unique=False, schema='public')
    op.create_index(op.f('IX_public_task_updated_at'), 'task', ['updated_at'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('IX_public_task_updated_at'), table_name='task', schema='public')
    op.drop_index(op.f('IX_public_task_created_at'), table_name='task', schema='public')
    op.drop_table('task', schema='public')
    op.drop_index(op.f('IX_public_employee_updated_at'), table_name='employee', schema='public')
    op.drop_index(op.f('IX_public_employee_created_at'), table_name='employee', schema='public')
    op.drop_table('employee', schema='public')
    # ### end Alembic commands ###
